/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package gradle_init_application_groovy_split.app

import gradle_init_application_groovy_split.list.LinkedList

import static gradle_init_application_groovy_split.utilities.StringUtils.join
import static gradle_init_application_groovy_split.utilities.StringUtils.split
import static gradle_init_application_groovy_split.app.MessageUtils.getMessage

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        println(join(tokens))
    }
}
