/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_init_application_java_split.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
