/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_init_application_java_split.app;

import gradle_init_application_java_split.list.LinkedList;

import static gradle_init_application_java_split.utilities.StringUtils.join;
import static gradle_init_application_java_split.utilities.StringUtils.split;
import static gradle_init_application_java_split.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
